server:
  port: 85

spring:
  application:
    name: zuul-demo

eureka:
  client:
    service-url:
      defaultZone: http://guzx:970712@${spring.cloud.client.ip-address}:8761/eureka

zuul:
  routes:
#    自定义名称，可以设置多个
    - persguzx:
       path: /persguzx/**
       url: http://www.baidu.com
    - perslianghong:
      path: /persliangh/**
      url: http://www.163.com