spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  task:
    pool:
      core-pool-size: 5
      max-pool-size: 50
      keep-alive-seconds: 60
      queue-capacity: 10000
      thread-name-prefix: GZX--
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        - beans
#        - mappings
#        - health
#        - user
  endpoint:
    health:
      show-details: ALWAYS