spring:
  application:
    name: consumer-service
  security:
    user:
      name: guzx
      password: 970712
server:
  port: 4569
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${spring.cloud.client.ip-address}:8761/eureka
  instance:
    #    采用ip注册
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://localhost:4569/actuator
