server:
  port: 2021
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: path_route
          uri: http://cxytiandi.com
          predicates:
#            - Path=/course
            - Path=/blog/user/**
        - id: eureka_route
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
        - id: query_route
          uri: http://cxytiandi.com
          predicates:
            - Query=foo,ba.
        - id: method_route
          uri: http://baidu.com
          predicates:
            - Method=GET
#          filters:
#            - AddRequestHeader=X
        - id: head_route
          uri: http://taobao.com
          predicates:
            - Header=X-Request-Id,\d+
#        - id: my_route
#          uri: http://www.163.com
#          predicates:
#            - name: CheckAuth
#              args:
#                name: yinjihuan
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://guzx:970712@${spring.cloud.client.ip-address}:8761/eureka
